"""
DAO 파일 생성기 (Java Interface)
SQL 정보를 받아 MyBatis Mapper Interface (Java) 코드를 생성합니다.
"""
import os
from typing import Dict, List, Optional
from pathlib import Path
from datetime import datetime
import sys

# 상위 디렉토리를 path에 추가
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from infra.config import snake_to_camel


class DAOGenerator:
    """
    DAO (MyBatis Mapper Interface) 생성 클래스
    
    SQL 정보를 받아 Java Interface 파일을 생성합니다.
    
    생성 예시:
        package com.example.dao;
        
        import org.apache.ibatis.annotations.Mapper;
        import java.util.List;
        import java.util.Map;
        
        @Mapper
        public interface SPAA0010Dao {
            List<Map<String, Object>> selectList(Map<String, Object> params);
            int updateStatus(Map<String, Object> params);
        }
    """
    
    def __init__(
        self,
        base_package: str,
        output_dir: Optional[str] = None
    ):
        """
        Args:
            base_package: Java 패키지 루트 (예: "com.example.dao")
            output_dir: 출력 디렉토리 (파일 저장할 경우)
        """
        self.base_package = base_package
        self.output_dir = output_dir
        
    def generate(
        self,
        sql_calls: List[Dict],
        id_to_path_map: Dict[str, str], # DTO 매핑 정보 (선택적)
        dao_name: str
    ) -> str:
        """
        DAO 인터페이스 소스 코드 생성
        
        Args:
            sql_calls: SQL 호출 정보 리스트
            id_to_path_map: SQL ID -> DTO 클래스 경로 매핑
            dao_name: DAO 인터페이스 이름
            
        Returns:
            Java 소스 코드 문자열
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        package_name = f"{self.base_package}"
        
        lines = []
        
        # Package definition
        lines.append(f"package {package_name};")
        lines.append("")
        
        # Imports
        lines.append("import org.apache.ibatis.annotations.Mapper;")
        lines.append("import java.util.List;")
        lines.append("import java.util.Map;")
        lines.append("import java.util.HashMap;")
        lines.append("")
        
        # Class comments
        lines.append("/**")
        lines.append(f" * Unnamed DAO - Generated by ProC Parser")
        lines.append(f" * Generated at: {timestamp}")
        lines.append(" */")
        
        # @Mapper annotation & Interface definition
        lines.append("@Mapper")
        lines.append(f"public interface {dao_name} {{")
        lines.append("")
        
        # SQL Methods
        for sql_obj in sql_calls:
            method_code = self._generate_method(sql_obj, id_to_path_map)
            lines.append(method_code)
            lines.append("")
            
        lines.append("}")
        
        return "\n".join(lines)
    
    def _generate_method(
        self,
        sql_obj: Dict,
        id_to_path_map: Dict[str, str]
    ) -> str:
        """
        단일 SQL 메소드 정의 생성
        """
        sql_id = sql_obj.get("name", "unnamedMethod")
        sql_type = sql_obj.get("sql_type", "select").lower()
        
        # Parameter type (DTO or Map)
        # 현재는 간단하게 Map<String, Object>를 기본으로 하되, 
        # id_to_path_map에 *In이 있으면 해당 DTO 사용 가능 (여기선 생략하고 Map/DTO 혼용 고려 안함)
        # 복잡성을 줄이기 위해 기본적으로 Map 사용
        param_type = "Map<String, Object>"
        
        # Return type determination
        if sql_type == "select":
            # List<Map<String, Object>> or List<Dto>
            # 단일 행 조회인지 판단하기 어려우므로 기본적으로 List 반환
            return_type = "List<Map<String, Object>>"
        elif sql_type in ("insert", "update", "delete"):
            return_type = "int"
        else:
            return_type = "void"
            
        # Method signature
        # 예: List<Map<String, Object>> selectList(Map<String, Object> params);
        
        # Javadoc comment
        comment = f"\t/**\n\t * SQL ID: {sql_id}\n\t * Type: {sql_type}\n\t */"
        
        method_sig = f"\t{return_type} {sql_id}({param_type} params);"
        
        return f"{comment}\n{method_sig}"

    def write(self, content: str, dao_name: str) -> str:
        """DAO 파일 저장"""
        if not self.output_dir:
            raise ValueError("output_dir가 설정되지 않았습니다")
            
        file_path = Path(self.output_dir) / f"{dao_name}.java"
        
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        return str(file_path)
